apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort  
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
      nodePort: 32001
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
