apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app_network: "true"
        io.kompose.service: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: zorro-solutions
      containers:
        - image: karageorge/ddm-frontend:1.87
          name: frontend
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://146.124.106.200/api
          resources: {}
      restartPolicy: Always
status: {}
