apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: zenoh4
  name: zenoh4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zenoh4
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app_network: "true"
        io.kompose.service: zenoh4
    spec:
      containers:
        - args:
            - -c
            - /root/.zenoh/zenoh-fs.json5
            - --adminspace-permissions
            - rw
          env:
            - name: RUST_LOG
              value: debug
            - name: ZENOH_BACKEND_FS_ROOT
              value: /root/.zenoh/fs
          image: eclipse/zenoh:0.11.0
          name: zenoh4
          ports:
            - containerPort: 7447
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /root/.zenoh
              name: zenoh4-claim0
      restartPolicy: Always
      volumes:
        - name: zenoh4-claim0
          persistentVolumeClaim:
            claimName: zenoh4-claim0
status: {}
