// utils/downloadHtmlReport.js

export const downloadHtmlReport = (file,isDarkMode) => {
    if (!file?.profileHtml) return;

    const themeColor = isDarkMode ? "#212529" : "#ffffff";
    const textColor = isDarkMode ? "#e0e0e0" : "#000000";
  

    const formattedHtml = `
       <!DOCTYPE html>
        <html>
            <head>
                <style>
                    body, html {
                        background-color: ${themeColor} !important;
                        color: ${textColor} !important;
                    }

                    /* 🔥 Fix tables */
                    table, th, td {
                        background-color: ${isDarkMode ? "#2c2f33" : "#ffffff"} !important;
                        color: ${textColor} !important;
                        border-color: ${isDarkMode ? "#444" : "#ccc"} !important;
                        width: 100% !important;
                    }

                    /* 🔥 Fix dropdowns */
                    .dropdown-menu, .dropdown-content, .select-menu, select {
                        background-color: ${isDarkMode ? "#343a40" : "#ffffff"} !important;
                        color: ${textColor} !important;
                        border-color: ${isDarkMode ? "#6c757d" : "#ccc"} !important;
                    }

                    /* 🔥 Fix selected tabs */
                    .nav-tabs .nav-link.active {
                        background-color: ${isDarkMode ? "#495057" : "#e9ecef"} !important;
                        color: ${isDarkMode ? "#ffffff" : "#000000"} !important;
                        border-color: ${isDarkMode ? "#6c757d #6c757d #495057" : "#dee2e6 #dee2e6 #ffffff"} !important;
                    }

                    /* 🔥 Fix buttons */
                    .btn, button {
                        background-color: ${isDarkMode ? "#444" : "#ffffff"} !important;
                        color: ${isDarkMode ? "#e0e0e0" : "#000000"} !important;
                        border-color: ${isDarkMode ? "#666" : "#ccc"} !important;
                        width: auto;
                    }

                    /* 🔥 Remove unwanted elements */
                    footer:contains('Report generated by YData') { display: none !important; }
                    p:contains('Brought to you by YData') { display: none !important; }
                </style>
            </head>
            <body>
                ${file.profileHtml}
                <script>
                    document.addEventListener("DOMContentLoaded", function () {
                        // Remove "Brought to you by YData"
                        let ydataText = Array.from(document.body.getElementsByTagName("p")).find(p => p.innerText.includes("Brought to you by YData"));
                        if (ydataText) ydataText.remove();

                        // Remove "Report generated by YData." in the footer
                        let footerText = Array.from(document.getElementsByTagName("footer")).find(footer => footer.innerText.includes("Report generated by YData."));
                        if (footerText) footerText.remove();
                        document.querySelectorAll("p.item-header a").forEach(link => {
                            const span = document.createElement("span"); // Create a plain <span>
                            span.innerHTML = link.innerHTML; // Preserve the text inside <a>
                            link.replaceWith(span); // Replace <a> with <span>
                        });

                        // Also remove standalone links (like the second example)
                        document.querySelectorAll("a").forEach(link => {
                            const span = document.createElement("span");
                            span.innerHTML = link.innerHTML;
                            link.replaceWith(span);
                        });
                        
                    });
                </script>
            </body>
        </html>
    `;

    const blob = new Blob([formattedHtml], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    const rawName = file?.name || file?.file?.name || "report";
    const fileName = rawName.replace(/\.[^/.]+$/, ""); // removes any extension
    a.download = `${fileName}_report.html`;

    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);

    URL.revokeObjectURL(url);
};
