// utils/htmlUtils.js

export const getHtmlReportStyles = (isDarkMode) => `
    <style>
    body, html {
        background-color: ${isDarkMode ? "#212529" : "#ffffff"} !important;
        color: ${isDarkMode ? "#e0e0e0" : "#000000"} !important;
    }

    /* 🔥 Fix for all tables */
    table, th, td {
        background-color: ${isDarkMode ? "#212529" : "#ffffff"} !important;
        color: ${isDarkMode ? "#e0e0e0" : "#000000"} !important;
        border-color: ${isDarkMode ? "#444" : "#ccc"} !important;
    }
    path {
        fill: ${isDarkMode ? "#212529" : "#ffffff"} !important;
        color: ${isDarkMode ? "#e0e0e0" : "#000000"} !important;
    }


    /* 🔥 Fix striped tables */
    .table-striped tbody tr:nth-of-type(odd),
    tr:nth-child(odd) {
        background-color: ${isDarkMode ? "#212529" : "#f8f9fa"} !important;
    }
    .table-hover tbody tr:hover {
        background-color: ${isDarkMode ? "#3e4449" : "#f1f1f1"} !important;
    }

    /* 🔥 Fix dropdowns & menus */
    .dropdown-menu, .dropdown-content, .select-menu, select {
        background-color: ${isDarkMode ? "#343a40" : "#ffffff"} !important;
        color: ${isDarkMode ? "#ffffff" : "#000000"} !important;
        border-color: ${isDarkMode ? "#6c757d" : "#ccc"} !important;
    }
    .dropdown-item:hover {
        background-color: ${isDarkMode ? "#495057" : "#f1f1f1"} !important;
    }

    /* 🔥 Fix selected tabs */
    .nav-tabs .nav-link.active {
        background-color: ${isDarkMode ? "#495057" : "#e9ecef"} !important;
        color: ${isDarkMode ? "#ffffff" : "#000000"} !important;
        border-color: ${isDarkMode ? "#6c757d #212529 #495057" : "#dee2e6 #dee2e6 #ffffff"} !important;
    }

    /* 🔥 Fix modal backgrounds */
    .modal-content {
        background-color: ${isDarkMode ? "#343a40" : "#ffffff"} !important;
        color: ${isDarkMode ? "#e0e0e0" : "#000000"} !important;
    }

    /* 🔥 Fix all buttons */
    .btn, button {
        background-color: ${isDarkMode ? "#212529" : "#ffffff"} !important;
        color: ${isDarkMode ? "#e0e0e0" : "#000000"} !important;
        border-color: ${isDarkMode ? "#666" : "#ccc"} !important;
    }
    .btn:hover, button:hover {
        background-color: ${isDarkMode ? "#555" : "#e0e0e0"} !important;
    }

    /* 🔥 Fix all links */
    a {
        color: ${isDarkMode ? "#bb86fc" : "#0d6efd"} !important;
    }
    a:hover {
        color: ${isDarkMode ? "#e0e0e0" : "#0056b3"} !important;
    }
    </style>
    `;
    export const getSanitizedHtml = (htmlContent, styles) => `
    <html>
      <head>${styles}</head>
      <body>
        ${htmlContent}
        <script>
          document.addEventListener("DOMContentLoaded", function () {
            let ydataText = Array.from(document.body.getElementsByTagName("p")).find(p => p.innerText.includes("Brought to you by YData"));
            if (ydataText) ydataText.remove();
  
            let footerText = Array.from(document.getElementsByTagName("footer")).find(footer => footer.innerText.includes("Report generated by YData."));
            if (footerText) footerText.remove();
  
            document.querySelectorAll("p.item-header a").forEach(link => {
              const span = document.createElement("span");
              span.innerHTML = link.innerHTML;
              link.replaceWith(span);
            });
  
            document.querySelectorAll("a").forEach(link => {
              const span = document.createElement("span");
              span.innerHTML = link.innerHTML;
              link.replaceWith(span);
            });
            
          });
        </script>
      </body>
    </html>
  `;
  